//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteUser_sp.
        /// </summary>
        internal static string SP_DeleteUser {
            get {
                return ResourceManager.GetString("SP_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadEmailAdd_sp.
        /// </summary>
        internal static string SP_LoadEmailAddress {
            get {
                return ResourceManager.GetString("SP_LoadEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadEmailTemplate_sp.
        /// </summary>
        internal static string SP_LoadEmailTemplate {
            get {
                return ResourceManager.GetString("SP_LoadEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadRoleByID_sp.
        /// </summary>
        internal static string SP_LoadRoleByID {
            get {
                return ResourceManager.GetString("SP_LoadRoleByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadUserByCode_sp.
        /// </summary>
        internal static string SP_LoadUserByCode {
            get {
                return ResourceManager.GetString("SP_LoadUserByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadUserByID_sp.
        /// </summary>
        internal static string SP_LoadUserByID {
            get {
                return ResourceManager.GetString("SP_LoadUserByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveEmailAdd_sp.
        /// </summary>
        internal static string SP_SaveEmailAddress {
            get {
                return ResourceManager.GetString("SP_SaveEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveEmailInfo_sp.
        /// </summary>
        internal static string SP_SaveEmailInfo {
            get {
                return ResourceManager.GetString("SP_SaveEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveEmailTemplate_sp.
        /// </summary>
        internal static string SP_SaveEmailTemplate {
            get {
                return ResourceManager.GetString("SP_SaveEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveLog_sp.
        /// </summary>
        internal static string SP_SaveLog {
            get {
                return ResourceManager.GetString("SP_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveUser_sp.
        /// </summary>
        internal static string SP_SaveUser {
            get {
                return ResourceManager.GetString("SP_SaveUser", resourceCulture);
            }
        }
    }
}
